# You should list any juggernaut hosts here.
# You need only specify the secret key if you're using that type of authentication (see juggernaut.yml)
# 
# Name:                       Mapping:
# :port                       internal push server's port
# :host                       internal push server's host/ip
# :public_host                public push server's host/ip (accessible from external clients)
# :public_port                public push server's port
# :secret_key (optional)      shared secret (should map to the key specified in the push server's config)
# :environment (optional)     limit host to a particular RAILS_ENV

:hosts:
  - :port: 5001
    :host: localhost
    :secret_key: 4c5a66845e65268178578a1eab2e79204d333e32011bd651440a19327d1b8c480a4b34739a68e537a9ff5707b23eaa88750c67f1e61ad22f3a02443d0fdbebb5
    # :environment: :development